### PR TITLE
Updated gdx to 1.9.10

### PR DESCRIPTION
**Pull request by piotr-j**
Only minor changes ware required. Ive tested stuff lightly, nothing seems to be obviously broken. Some deprecation warnings.

### CODE REVIEW

**Comment by kotcrab** [comment]
I'm going to release 1.4.3 as-is to avoid breaking existing builds relaying on snapshot version. Then update to 1.9.10 and release 1.4.4.

**Comment by kotcrab** [comment]
Released and merged your changes manually, thanks!

**Comment by kotcrab** [comment]
The CI server is down (and will stay that way) so I'm uploading snapshot manually. One possible thing to contribute would be adding Travis integration but that's probably hard without access to the repository.

**Comment by piotr-j** [comment]
Afraid i dont have any travis-ci experience, did circle-ci stuff once for a bit. Probably woulnt be too hard, since releases are setup already

**Comment by kotcrab** [comment]
It's okay, no worries. I would have to do it anyway because it needs setting up login details for Maven Central. On the other hand it's not like there is a lot of activity going on here.

**Comment by metaphore** [comment]
Hey @kotcrab, any plans to publish a release version with 1.9.10 support soon?

I'm working on [LML](https://github.com/czyzby/gdx-lml) library 1.9.10 compatibility and `lml-vis` module depends on the release version of `vis-ui`. I'd would appreciate if you could publish it soon, this way I can push updates on the `LML` side of things quicker (the lib didn't get any updates since LibGDX 1.9.8).

**Comment by kotcrab** [comment]
No problem, I can release it today.

**Comment by kotcrab** [comment]
@metaphore Done. OSS Nexus is very slow today so don't know when that's going to be available.

**Comment by metaphore** [comment]
@kotcrab thanks a lot, that was blazing fast!

**Pull request closed without merging**
