### PR TITLE
Upgrade to libGDX 1.9.12

### PR DESCRIPTION
**Pull request by fgnm**
I've upgrade to new libGDX version and fixed scrolled breaking change.

Regards :)

### CODE REVIEW

**Comment by kotcrab** [comment]
Thanks! This is a breaking change though. I'll have to release current version before merging this.

**Comment by piotr-j** [comment]
Oops didnt check before my own PR. Im not sure about that Spinner change, ill check how it works on a mac.

**Comment by Frotty** [comment]
Would be nice to have this merged asap.

**Comment by kotcrab** [comment]
I'll try to do release over the weekend.

**Comment by kotcrab** [comment]
Done, released for both versions:
| VisUI              | LibGDX             |
| ------------------ | ------------------ |
| 1.4.7              | 1.9.11             |
| 1.4.8              | 1.9.12             |
| 1.4.9-SNAPSHOT     | 1.9.12             |

I've changed it like in #345. I don't see why spinner should also use `amountX`.

**Pull request closed without merging**
