### PR TITLE
Update to libGDX 1.10.0

### PR DESCRIPTION
**Pull request by czyzby**

### CODE REVIEW

**Review by kotcrab — APPROVED** [review]

**Comment by kotcrab** [comment]
I approved too fast, there's also this field to update https://github.com/kotcrab/vis-ui/blob/master/ui/src/main/java/com/kotcrab/vis/ui/VisUI.java#L33

**Comment by czyzby** [comment]
@kotcrab Thanks, missed it. Please take a look.

**Review by kotcrab — APPROVED** [review]
Yep, all okay now.

**Comment by kotcrab** [comment]
@czyzby do you want me to merge this and do a release?

**Comment by czyzby** [comment]
I can do the merge and trigger the pipeline, just wanted to make sure I did everything to update the version.

**Pull request merged**
